#!/bin/bash

# Display listening sockets with PID and program name
netstat -tlnp | awk 'NR > 2 {print $1, $4, $7}' | sed 's/.*://' | awk '{print $1, $2}' | while read proto addr pid_program
do
    pid=$(echo $pid_program | cut -d / -f 1)
    program=$(echo $pid_program | cut -d / -f 2-)
    echo "$proto $addr $pid $program"
done
